project               = "yuto-gcp-playground"
location              = "asia-northeast1"
repo_name             = "mipo1357/gcp_playground"
container_image       = "gcr.io/cloudrun/hello"
db_user_password      = "root"
db_root_user_password = "root"
